live_config_reload = true
import = [
	"~/.config/alacritty/themes/themes/gruvbox_dark.toml",
]

[window]
decorations = "Buttonless"
opacity = 0.9
blur =  false
option_as_alt = "Both"

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }
size = 14

[selection]
save_to_clipboard = true

#[shell]
#program = "/opt/homebrew/bin/zsh"
#args = ["--login", "-c", "tmux a -t base || tmux new -s base"]
